// Mock data for development
export const mockCategories = [
    { id: 1, name: 'Home', slug: 'home' },
    { id: 2, name: 'Sri Lanka', slug: 'sri-lanka' },
    { id: 3, name: 'Political', slug: 'political' },
    { id: 4, name: 'Feature', slug: 'feature' },
    { id: 5, name: 'International', slug: 'international' },
    { id: 6, name: 'Other', slug: 'other' },
];

export const mockPosts = [
    {
        "id": 1,
        "title": "ශ්‍රී ලංකාවේ නව ආර්ථික ප්‍රතිසංස්කරණ ප්‍රකාශයට පත් කෙරේ",
        "slug": "sri-lanka-post-1",
        "excerpt": "රජය විසින් නව ආර්ථික ප්‍රතිසංස්කරණ පැකේජයක් ප්‍රකාශයට පත් කර ඇත.",
        "content": "<p>රජය විසින් නව ආර්ථික ප්‍රතිසංස්කරණ පැකේජයක් ප්‍රකාශයට පත් කර ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=500&fit=crop",
        "categoryId": 2,
        "categoryName": "Sri Lanka",
        "language": "si",
        "postType": "article",
        "viewCount": 537,
        "publishedAt": "2026-02-13T07:00:00Z",
        "createdAt": "2026-02-13T06:00:00Z"
    },
    {
        "id": 2,
        "title": "කොළඹ නගරයේ නව මාර්ග සංවර්ධන ව්‍යාපෘතිය ආරම්භ වේ",
        "slug": "sri-lanka-post-2",
        "excerpt": "කොළඹ නගරයේ තදබදය අවම කිරීම සඳහා නව මාර්ග සංවර්ධන ව්‍යාපෘතියක් ආරම්භ කර ඇත.",
        "content": "<p>කොළඹ නගරයේ තදබදය අවම කිරීම සඳහා නව මාර්ග සංවර්ධන ව්‍යාපෘතියක් ආරම්භ කර ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=500&fit=crop",
        "categoryId": 2,
        "categoryName": "Sri Lanka",
        "language": "si",
        "postType": "video",
        "viewCount": 574,
        "publishedAt": "2026-02-13T04:00:00Z",
        "createdAt": "2026-02-13T03:00:00Z",
        "videoId": "jNQXAC9IVRw"
    },
    {
        "id": 3,
        "title": "Sri Lanka Tourism Industry Shows Strong Recovery",
        "slug": "sri-lanka-post-3",
        "excerpt": "The tourism sector reports a 45% increase in visitor arrivals this quarter.",
        "content": "<p>The tourism sector reports a 45% increase in visitor arrivals this quarter.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=500&fit=crop",
        "categoryId": 2,
        "categoryName": "Sri Lanka",
        "language": "en",
        "postType": "article",
        "viewCount": 611,
        "publishedAt": "2026-02-13T01:00:00Z",
        "createdAt": "2026-02-13T00:00:00Z"
    },
    {
        "id": 4,
        "title": "නව තාක්ෂණික උද්‍යාන සංකීර්ණය විවෘත කෙරේ",
        "slug": "sri-lanka-post-4",
        "excerpt": "රජය විසින් නව තාක්ෂණික උද්‍යාන සංකීර්ණයක් විවෘත කර ඇත.",
        "content": "<p>රජය විසින් නව තාක්ෂණික උද්‍යාන සංකීර්ණයක් විවෘත කර ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=500&fit=crop",
        "categoryId": 2,
        "categoryName": "Sri Lanka",
        "language": "si",
        "postType": "audio",
        "viewCount": 648,
        "publishedAt": "2026-02-12T22:00:00Z",
        "createdAt": "2026-02-12T21:00:00Z",
        "audioId": "fJ9rUzIMcZQ"
    },
    {
        "id": 5,
        "title": "Port City Colombo Development Reaches New Milestone",
        "slug": "sri-lanka-post-5",
        "excerpt": "Major infrastructure projects completed ahead of schedule.",
        "content": "<p>Major infrastructure projects completed ahead of schedule.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&h=500&fit=crop",
        "categoryId": 2,
        "categoryName": "Sri Lanka",
        "language": "en",
        "postType": "article",
        "viewCount": 685,
        "publishedAt": "2026-02-12T19:00:00Z",
        "createdAt": "2026-02-12T18:00:00Z"
    },
    {
        "id": 6,
        "title": "ශ්‍රී ලංකාවේ අපනයන ආදායම වැඩි වේ",
        "slug": "sri-lanka-post-6",
        "excerpt": "මෙම වසරේ අපනයන ආදායම 20%කින් වැඩි වී ඇත.",
        "content": "<p>මෙම වසරේ අපනයන ආදායම 20%කින් වැඩි වී ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=500&fit=crop",
        "categoryId": 2,
        "categoryName": "Sri Lanka",
        "language": "si",
        "postType": "video",
        "viewCount": 722,
        "publishedAt": "2026-02-12T16:00:00Z",
        "createdAt": "2026-02-12T15:00:00Z",
        "videoId": "jNQXAC9IVRw"
    },
    {
        "id": 7,
        "title": "New Railway Line Connecting North and South Opens",
        "slug": "sri-lanka-post-7",
        "excerpt": "Historic railway connection improves transportation across the island.",
        "content": "<p>Historic railway connection improves transportation across the island.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&h=500&fit=crop",
        "categoryId": 2,
        "categoryName": "Sri Lanka",
        "language": "en",
        "postType": "article",
        "viewCount": 759,
        "publishedAt": "2026-02-12T13:00:00Z",
        "createdAt": "2026-02-12T12:00:00Z"
    },
    {
        "id": 8,
        "title": "පාරිසරික සංරක්ෂණ ව්‍යාපෘති ආරම්භ වේ",
        "slug": "sri-lanka-post-8",
        "excerpt": "රජය විසින් නව පාරිසරික සංරක්ෂණ ව්‍යාපෘති මාලාවක් ආරම්භ කර ඇත.",
        "content": "<p>රජය විසින් නව පාරිසරික සංරක්ෂණ ව්‍යාපෘති මාලාවක් ආරම්භ කර ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800&h=500&fit=crop",
        "categoryId": 2,
        "categoryName": "Sri Lanka",
        "language": "si",
        "postType": "audio",
        "viewCount": 796,
        "publishedAt": "2026-02-12T10:00:00Z",
        "createdAt": "2026-02-12T09:00:00Z",
        "audioId": "fJ9rUzIMcZQ"
    },
    {
        "id": 9,
        "title": "Sri Lanka Wins International Award for Sustainable Development",
        "slug": "sri-lanka-post-9",
        "excerpt": "Country recognized for environmental conservation efforts.",
        "content": "<p>Country recognized for environmental conservation efforts.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=500&fit=crop",
        "categoryId": 2,
        "categoryName": "Sri Lanka",
        "language": "en",
        "postType": "article",
        "viewCount": 833,
        "publishedAt": "2026-02-12T07:00:00Z",
        "createdAt": "2026-02-12T06:00:00Z"
    },
    {
        "id": 10,
        "title": "නව රැකියා අවස්ථා 50,000ක් නිර්මාණය වේ",
        "slug": "sri-lanka-post-10",
        "excerpt": "ආර්ථික ප්‍රතිසංස්කරණ මගින් නව රැකියා අවස්ථා නිර්මාණය වී ඇත.",
        "content": "<p>ආර්ථික ප්‍රතිසංස්කරණ මගින් නව රැකියා අවස්ථා නිර්මාණය වී ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=500&fit=crop",
        "categoryId": 2,
        "categoryName": "Sri Lanka",
        "language": "si",
        "postType": "video",
        "viewCount": 870,
        "publishedAt": "2026-02-12T04:00:00Z",
        "createdAt": "2026-02-12T03:00:00Z",
        "videoId": "jNQXAC9IVRw"
    },
    {
        "id": 11,
        "title": "Digital Infrastructure Expansion Announced",
        "slug": "sri-lanka-post-11",
        "excerpt": "Nationwide 5G network rollout to begin next quarter.",
        "content": "<p>Nationwide 5G network rollout to begin next quarter.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=500&fit=crop",
        "categoryId": 2,
        "categoryName": "Sri Lanka",
        "language": "en",
        "postType": "article",
        "viewCount": 907,
        "publishedAt": "2026-02-12T01:00:00Z",
        "createdAt": "2026-02-12T00:00:00Z"
    },
    {
        "id": 12,
        "title": "ශ්‍රී ලංකාව ආසියාතික ආර්ථික සමුළුව පවත්වයි",
        "slug": "sri-lanka-post-12",
        "excerpt": "කොළඹ නගරයේ ප්‍රධාන ආසියාතික ආර්ථික සමුළුව පැවැත්වේ.",
        "content": "<p>කොළඹ නගරයේ ප්‍රධාන ආසියාතික ආර්ථික සමුළුව පැවැත්වේ.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=500&fit=crop",
        "categoryId": 2,
        "categoryName": "Sri Lanka",
        "language": "si",
        "postType": "audio",
        "viewCount": 944,
        "publishedAt": "2026-02-11T22:00:00Z",
        "createdAt": "2026-02-11T21:00:00Z",
        "audioId": "fJ9rUzIMcZQ"
    },
    {
        "id": 13,
        "title": "New Infrastructure Development Plan Unveiled",
        "slug": "political-post-1",
        "excerpt": "Government announces ambitious infrastructure development plan.",
        "content": "<p>Government announces ambitious infrastructure development plan.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=500&fit=crop",
        "categoryId": 3,
        "categoryName": "Political",
        "language": "en",
        "postType": "article",
        "viewCount": 981,
        "publishedAt": "2026-02-11T19:00:00Z",
        "createdAt": "2026-02-11T18:00:00Z"
    },
    {
        "id": 14,
        "title": "Education Reform Bill Passes Parliament",
        "slug": "political-post-2",
        "excerpt": "Parliament passes comprehensive education reform bill.",
        "content": "<p>Parliament passes comprehensive education reform bill.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=500&fit=crop",
        "categoryId": 3,
        "categoryName": "Political",
        "language": "en",
        "postType": "video",
        "viewCount": 1018,
        "publishedAt": "2026-02-11T16:00:00Z",
        "createdAt": "2026-02-11T15:00:00Z",
        "videoId": "jNQXAC9IVRw"
    },
    {
        "id": 15,
        "title": "පාර්ලිමේන්තුව නව බදු ප්‍රතිසංස්කරණ අනුමත කරයි",
        "slug": "political-post-3",
        "excerpt": "නව බදු ප්‍රතිසංස්කරණ පනත් කෙටුම්පත අනුමත කර ඇත.",
        "content": "<p>නව බදු ප්‍රතිසංස්කරණ පනත් කෙටුම්පත අනුමත කර ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=500&fit=crop",
        "categoryId": 3,
        "categoryName": "Political",
        "language": "si",
        "postType": "article",
        "viewCount": 1055,
        "publishedAt": "2026-02-11T13:00:00Z",
        "createdAt": "2026-02-11T12:00:00Z"
    },
    {
        "id": 16,
        "title": "Opposition Proposes Alternative Economic Strategy",
        "slug": "political-post-4",
        "excerpt": "Opposition parties present comprehensive economic plan.",
        "content": "<p>Opposition parties present comprehensive economic plan.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=500&fit=crop",
        "categoryId": 3,
        "categoryName": "Political",
        "language": "en",
        "postType": "audio",
        "viewCount": 1092,
        "publishedAt": "2026-02-11T10:00:00Z",
        "createdAt": "2026-02-11T09:00:00Z",
        "audioId": "fJ9rUzIMcZQ"
    },
    {
        "id": 17,
        "title": "ආණ්ඩුව නව සෞඛ්‍ය ප්‍රතිපත්ති ප්‍රකාශයට පත් කරයි",
        "slug": "political-post-5",
        "excerpt": "රජය විසින් නව සෞඛ්‍ය ප්‍රතිපත්ති පැකේජයක් ප්‍රකාශයට පත් කර ඇත.",
        "content": "<p>රජය විසින් නව සෞඛ්‍ය ප්‍රතිපත්ති පැකේජයක් ප්‍රකාශයට පත් කර ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&h=500&fit=crop",
        "categoryId": 3,
        "categoryName": "Political",
        "language": "si",
        "postType": "video",
        "viewCount": 1129,
        "publishedAt": "2026-02-11T07:00:00Z",
        "createdAt": "2026-02-11T06:00:00Z",
        "videoId": "dQw4w9WgXcQ"
    },
    {
        "id": 18,
        "title": "Parliament Debates Climate Change Legislation",
        "slug": "political-post-6",
        "excerpt": "New environmental protection laws under consideration.",
        "content": "<p>New environmental protection laws under consideration.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=500&fit=crop",
        "categoryId": 3,
        "categoryName": "Political",
        "language": "en",
        "postType": "article",
        "viewCount": 1166,
        "publishedAt": "2026-02-11T04:00:00Z",
        "createdAt": "2026-02-11T03:00:00Z"
    },
    {
        "id": 19,
        "title": "නව අධිකරණ ප්‍රතිසංස්කරණ යෝජනා කෙරේ",
        "slug": "political-post-7",
        "excerpt": "අධිකරණ පද්ධතිය නවීකරණය කිරීම සඳහා යෝජනා ඉදිරිපත් කර ඇත.",
        "content": "<p>අධිකරණ පද්ධතිය නවීකරණය කිරීම සඳහා යෝජනා ඉදිරිපත් කර ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&h=500&fit=crop",
        "categoryId": 3,
        "categoryName": "Political",
        "language": "si",
        "postType": "audio",
        "viewCount": 1203,
        "publishedAt": "2026-02-11T01:00:00Z",
        "createdAt": "2026-02-11T00:00:00Z",
        "audioId": "60ItHLz5WEA"
    },
    {
        "id": 20,
        "title": "Government Announces Anti-Corruption Measures",
        "slug": "political-post-8",
        "excerpt": "New transparency initiatives launched to combat corruption.",
        "content": "<p>New transparency initiatives launched to combat corruption.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800&h=500&fit=crop",
        "categoryId": 3,
        "categoryName": "Political",
        "language": "en",
        "postType": "article",
        "viewCount": 1240,
        "publishedAt": "2026-02-10T22:00:00Z",
        "createdAt": "2026-02-10T21:00:00Z"
    },
    {
        "id": 21,
        "title": "පළාත් සභා ප්‍රතිසංස්කරණ පනත් කෙටුම්පත ඉදිරිපත් වේ",
        "slug": "political-post-9",
        "excerpt": "පළාත් සභා පද්ධතිය ශක්තිමත් කිරීම සඳහා නව පනත් කෙටුම්පතක් ඉදිරිපත් කර ඇත.",
        "content": "<p>පළාත් සභා පද්ධතිය ශක්තිමත් කිරීම සඳහා නව පනත් කෙටුම්පතක් ඉදිරිපත් කර ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=500&fit=crop",
        "categoryId": 3,
        "categoryName": "Political",
        "language": "si",
        "postType": "video",
        "viewCount": 1277,
        "publishedAt": "2026-02-10T19:00:00Z",
        "createdAt": "2026-02-10T18:00:00Z",
        "videoId": "dQw4w9WgXcQ"
    },
    {
        "id": 22,
        "title": "Coalition Government Reaches Agreement on Budget",
        "slug": "political-post-10",
        "excerpt": "Major political parties agree on national budget priorities.",
        "content": "<p>Major political parties agree on national budget priorities.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=500&fit=crop",
        "categoryId": 3,
        "categoryName": "Political",
        "language": "en",
        "postType": "article",
        "viewCount": 1314,
        "publishedAt": "2026-02-10T16:00:00Z",
        "createdAt": "2026-02-10T15:00:00Z"
    },
    {
        "id": 23,
        "title": "නව ඡන්ද ප්‍රතිසංස්කරණ යෝජනා කෙරේ",
        "slug": "political-post-11",
        "excerpt": "ඡන්ද පද්ධතිය නවීකරණය කිරීම සඳහා යෝජනා ඉදිරිපත් වී ඇත.",
        "content": "<p>ඡන්ද පද්ධතිය නවීකරණය කිරීම සඳහා යෝජනා ඉදිරිපත් වී ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=500&fit=crop",
        "categoryId": 3,
        "categoryName": "Political",
        "language": "si",
        "postType": "audio",
        "viewCount": 1351,
        "publishedAt": "2026-02-10T13:00:00Z",
        "createdAt": "2026-02-10T12:00:00Z",
        "audioId": "60ItHLz5WEA"
    },
    {
        "id": 24,
        "title": "Parliament Approves Constitutional Amendment",
        "slug": "political-post-12",
        "excerpt": "Historic constitutional changes passed with bipartisan support.",
        "content": "<p>Historic constitutional changes passed with bipartisan support.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=500&fit=crop",
        "categoryId": 3,
        "categoryName": "Political",
        "language": "en",
        "postType": "article",
        "viewCount": 1388,
        "publishedAt": "2026-02-10T10:00:00Z",
        "createdAt": "2026-02-10T09:00:00Z"
    },
    {
        "id": 25,
        "title": "පාරිසරික සංරක්ෂණය සඳහා නව ව්‍යාපෘති ආරම්භ වේ",
        "slug": "feature-post-1",
        "excerpt": "රජය විසින් පාරිසරික සංරක්ෂණය සඳහා නව ව්‍යාපෘති මාලාවක් ආරම්භ කර ඇත.",
        "content": "<p>රජය විසින් පාරිසරික සංරක්ෂණය සඳහා නව ව්‍යාපෘති මාලාවක් ආරම්භ කර ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=500&fit=crop",
        "categoryId": 4,
        "categoryName": "Feature",
        "language": "si",
        "postType": "article",
        "viewCount": 1425,
        "publishedAt": "2026-02-10T07:00:00Z",
        "createdAt": "2026-02-10T06:00:00Z"
    },
    {
        "id": 26,
        "title": "The Rise of Sustainable Agriculture in Rural Communities",
        "slug": "feature-post-2",
        "excerpt": "Farmers embrace eco-friendly farming practices with remarkable results.",
        "content": "<p>Farmers embrace eco-friendly farming practices with remarkable results.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=500&fit=crop",
        "categoryId": 4,
        "categoryName": "Feature",
        "language": "en",
        "postType": "video",
        "viewCount": 1462,
        "publishedAt": "2026-02-10T04:00:00Z",
        "createdAt": "2026-02-10T03:00:00Z",
        "videoId": "jNQXAC9IVRw"
    },
    {
        "id": 27,
        "title": "සංස්කෘතික උරුමය සුරැකීමේ නව මුලපිරීම",
        "slug": "feature-post-3",
        "excerpt": "පුරාවිද්‍යා දෙපාර්තමේන්තුව විසින් සංස්කෘතික උරුමය සුරැකීමේ නව වැඩසටහනක් ආරම්භ කර ඇත.",
        "content": "<p>පුරාවිද්‍යා දෙපාර්තමේන්තුව විසින් සංස්කෘතික උරුමය සුරැකීමේ නව වැඩසටහනක් ආරම්භ කර ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=500&fit=crop",
        "categoryId": 4,
        "categoryName": "Feature",
        "language": "si",
        "postType": "audio",
        "viewCount": 1499,
        "publishedAt": "2026-02-10T01:00:00Z",
        "createdAt": "2026-02-10T00:00:00Z",
        "audioId": "60ItHLz5WEA"
    },
    {
        "id": 28,
        "title": "Women Entrepreneurs Transform Local Economy",
        "slug": "feature-post-4",
        "excerpt": "Success stories of women-led businesses inspiring communities.",
        "content": "<p>Success stories of women-led businesses inspiring communities.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=500&fit=crop",
        "categoryId": 4,
        "categoryName": "Feature",
        "language": "en",
        "postType": "article",
        "viewCount": 1536,
        "publishedAt": "2026-02-09T22:00:00Z",
        "createdAt": "2026-02-09T21:00:00Z"
    },
    {
        "id": 29,
        "title": "තරුණ නවෝත්පාදකයින් තාක්ෂණික විසඳුම් නිර්මාණය කරති",
        "slug": "feature-post-5",
        "excerpt": "තරුණ තරුණියන් විසින් නව තාක්ෂණික විසඳුම් නිර්මාණය කර ඇත.",
        "content": "<p>තරුණ තරුණියන් විසින් නව තාක්ෂණික විසඳුම් නිර්මාණය කර ඇත.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&h=500&fit=crop",
        "categoryId": 4,
        "categoryName": "Feature",
        "language": "si",
        "postType": "video",
        "viewCount": 1573,
        "publishedAt": "2026-02-09T19:00:00Z",
        "createdAt": "2026-02-09T18:00:00Z",
        "videoId": "dQw4w9WgXcQ"
    },
    {
        "id": 30,
        "title": "Traditional Crafts Experience Modern Revival",
        "slug": "feature-post-6",
        "excerpt": "Ancient art forms find new life through contemporary adaptations.",
        "content": "<p>Ancient art forms find new life through contemporary adaptations.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=500&fit=crop",
        "categoryId": 4,
        "categoryName": "Feature",
        "language": "en",
        "postType": "article",
        "viewCount": 1610,
        "publishedAt": "2026-02-09T16:00:00Z",
        "createdAt": "2026-02-09T15:00:00Z"
    },
    {
        "id": 31,
        "title": "අධ්‍යාපන ක්ෂේත්‍රයේ නව්‍ය ප්‍රවේශයන්",
        "slug": "feature-post-7",
        "excerpt": "ගුරුවරුන් විසින් නව්‍ය අධ්‍යාපන ක්‍රම භාවිතා කරති.",
        "content": "<p>ගුරුවරුන් විසින් නව්‍ය අධ්‍යාපන ක්‍රම භාවිතා කරති.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&h=500&fit=crop",
        "categoryId": 4,
        "categoryName": "Feature",
        "language": "si",
        "postType": "audio",
        "viewCount": 1647,
        "publishedAt": "2026-02-09T13:00:00Z",
        "createdAt": "2026-02-09T12:00:00Z",
        "audioId": "60ItHLz5WEA"
    },
    {
        "id": 32,
        "title": "Community-Led Conservation Efforts Show Promising Results",
        "slug": "feature-post-8",
        "excerpt": "Local initiatives protect endangered species and habitats.",
        "content": "<p>Local initiatives protect endangered species and habitats.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800&h=500&fit=crop",
        "categoryId": 4,
        "categoryName": "Feature",
        "language": "en",
        "postType": "article",
        "viewCount": 1684,
        "publishedAt": "2026-02-09T10:00:00Z",
        "createdAt": "2026-02-09T09:00:00Z"
    },
    {
        "id": 33,
        "title": "ග්‍රාමීය සංවර්ධනයේ සාර්ථක කථා",
        "slug": "feature-post-9",
        "excerpt": "ග්‍රාමීය ප්‍රජාවන් සංවර්ධනය සඳහා නව මාර්ග සොයයි.",
        "content": "<p>ග්‍රාමීය ප්‍රජාවන් සංවර්ධනය සඳහා නව මාර්ග සොයයි.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=500&fit=crop",
        "categoryId": 4,
        "categoryName": "Feature",
        "language": "si",
        "postType": "video",
        "viewCount": 1721,
        "publishedAt": "2026-02-09T07:00:00Z",
        "createdAt": "2026-02-09T06:00:00Z",
        "videoId": "dQw4w9WgXcQ"
    },
    {
        "id": 34,
        "title": "Digital Literacy Programs Transform Education",
        "slug": "feature-post-10",
        "excerpt": "Technology integration improves learning outcomes nationwide.",
        "content": "<p>Technology integration improves learning outcomes nationwide.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=500&fit=crop",
        "categoryId": 4,
        "categoryName": "Feature",
        "language": "en",
        "postType": "article",
        "viewCount": 1758,
        "publishedAt": "2026-02-09T04:00:00Z",
        "createdAt": "2026-02-09T03:00:00Z"
    },
    {
        "id": 35,
        "title": "සෞඛ්‍ය සේවා ක්ෂේත්‍රයේ නව්‍යකරණ",
        "slug": "feature-post-11",
        "excerpt": "සෞඛ්‍ය සේවා ක්ෂේත්‍රයේ නව තාක්ෂණික ප්‍රගතිය.",
        "content": "<p>සෞඛ්‍ය සේවා ක්ෂේත්‍රයේ නව තාක්ෂණික ප්‍රගතිය.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=500&fit=crop",
        "categoryId": 4,
        "categoryName": "Feature",
        "language": "si",
        "postType": "audio",
        "viewCount": 1795,
        "publishedAt": "2026-02-09T01:00:00Z",
        "createdAt": "2026-02-09T00:00:00Z",
        "audioId": "60ItHLz5WEA"
    },
    {
        "id": 36,
        "title": "Youth-Led Social Enterprises Making Impact",
        "slug": "feature-post-12",
        "excerpt": "Young entrepreneurs address social challenges through business.",
        "content": "<p>Young entrepreneurs address social challenges through business.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=500&fit=crop",
        "categoryId": 4,
        "categoryName": "Feature",
        "language": "en",
        "postType": "article",
        "viewCount": 1832,
        "publishedAt": "2026-02-08T22:00:00Z",
        "createdAt": "2026-02-08T21:00:00Z"
    },
    {
        "id": 37,
        "title": "International Trade Summit Concludes with Major Agreements",
        "slug": "international-post-1",
        "excerpt": "Multiple bilateral trade agreements signed between nations.",
        "content": "<p>Multiple bilateral trade agreements signed between nations.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=500&fit=crop",
        "categoryId": 5,
        "categoryName": "International",
        "language": "en",
        "postType": "article",
        "viewCount": 1869,
        "publishedAt": "2026-02-08T19:00:00Z",
        "createdAt": "2026-02-08T18:00:00Z"
    },
    {
        "id": 38,
        "title": "Global Climate Conference Reaches Historic Agreement",
        "slug": "international-post-2",
        "excerpt": "World leaders commit to ambitious carbon reduction targets.",
        "content": "<p>World leaders commit to ambitious carbon reduction targets.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=500&fit=crop",
        "categoryId": 5,
        "categoryName": "International",
        "language": "en",
        "postType": "video",
        "viewCount": 1906,
        "publishedAt": "2026-02-08T16:00:00Z",
        "createdAt": "2026-02-08T15:00:00Z",
        "videoId": "jNQXAC9IVRw"
    },
    {
        "id": 39,
        "title": "ආසියා පැසිෆික් කලාපයේ ආර්ථික වර්ධනය වේගවත් වේ",
        "slug": "international-post-3",
        "excerpt": "කලාපීය ආර්ථික වර්ධනය අපේක්ෂිත මට්ටම් ඉක්මවයි.",
        "content": "<p>කලාපීය ආර්ථික වර්ධනය අපේක්ෂිත මට්ටම් ඉක්මවයි.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=500&fit=crop",
        "categoryId": 5,
        "categoryName": "International",
        "language": "si",
        "postType": "audio",
        "viewCount": 1943,
        "publishedAt": "2026-02-08T13:00:00Z",
        "createdAt": "2026-02-08T12:00:00Z",
        "audioId": "60ItHLz5WEA"
    },
    {
        "id": 40,
        "title": "UN Security Council Addresses Regional Conflicts",
        "slug": "international-post-4",
        "excerpt": "International community seeks peaceful resolutions.",
        "content": "<p>International community seeks peaceful resolutions.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=500&fit=crop",
        "categoryId": 5,
        "categoryName": "International",
        "language": "en",
        "postType": "article",
        "viewCount": 1980,
        "publishedAt": "2026-02-08T10:00:00Z",
        "createdAt": "2026-02-08T09:00:00Z"
    },
    {
        "id": 41,
        "title": "ජාත්‍යන්තර තාක්ෂණික සමුළුව සාර්ථකව අවසන් වේ",
        "slug": "international-post-5",
        "excerpt": "ප්‍රධාන තාක්ෂණික සමුළුව නව සහයෝගීතා ඇති කරයි.",
        "content": "<p>ප්‍රධාන තාක්ෂණික සමුළුව නව සහයෝගීතා ඇති කරයි.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&h=500&fit=crop",
        "categoryId": 5,
        "categoryName": "International",
        "language": "si",
        "postType": "video",
        "viewCount": 2017,
        "publishedAt": "2026-02-08T07:00:00Z",
        "createdAt": "2026-02-08T06:00:00Z",
        "videoId": "dQw4w9WgXcQ"
    },
    {
        "id": 42,
        "title": "Global Health Organization Launches New Initiative",
        "slug": "international-post-6",
        "excerpt": "Worldwide vaccination program aims to eradicate diseases.",
        "content": "<p>Worldwide vaccination program aims to eradicate diseases.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=500&fit=crop",
        "categoryId": 5,
        "categoryName": "International",
        "language": "en",
        "postType": "article",
        "viewCount": 2054,
        "publishedAt": "2026-02-08T04:00:00Z",
        "createdAt": "2026-02-08T03:00:00Z"
    },
    {
        "id": 43,
        "title": "ජාත්‍යන්තර ක්‍රීඩා උළෙල සඳහා සූදානම",
        "slug": "international-post-7",
        "excerpt": "ප්‍රධාන ජාත්‍යන්තර ක්‍රීඩා උළෙල සඳහා සූදානම් කටයුතු ආරම්භ වේ.",
        "content": "<p>ප්‍රධාන ජාත්‍යන්තර ක්‍රීඩා උළෙල සඳහා සූදානම් කටයුතු ආරම්භ වේ.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&h=500&fit=crop",
        "categoryId": 5,
        "categoryName": "International",
        "language": "si",
        "postType": "audio",
        "viewCount": 2091,
        "publishedAt": "2026-02-08T01:00:00Z",
        "createdAt": "2026-02-08T00:00:00Z",
        "audioId": "60ItHLz5WEA"
    },
    {
        "id": 44,
        "title": "World Economic Forum Discusses Future of Work",
        "slug": "international-post-8",
        "excerpt": "Leaders debate automation and employment challenges.",
        "content": "<p>Leaders debate automation and employment challenges.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800&h=500&fit=crop",
        "categoryId": 5,
        "categoryName": "International",
        "language": "en",
        "postType": "article",
        "viewCount": 2128,
        "publishedAt": "2026-02-07T22:00:00Z",
        "createdAt": "2026-02-07T21:00:00Z"
    },
    {
        "id": 45,
        "title": "ජාත්‍යන්තර අධ්‍යාපන සමුළුව පවත්වයි",
        "slug": "international-post-9",
        "excerpt": "අධ්‍යාපන ප්‍රතිසංස්කරණ පිළිබඳ ජාත්‍යන්තර සංවාදය.",
        "content": "<p>අධ්‍යාපන ප්‍රතිසංස්කරණ පිළිබඳ ජාත්‍යන්තර සංවාදය.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=500&fit=crop",
        "categoryId": 5,
        "categoryName": "International",
        "language": "si",
        "postType": "video",
        "viewCount": 2165,
        "publishedAt": "2026-02-07T19:00:00Z",
        "createdAt": "2026-02-07T18:00:00Z",
        "videoId": "dQw4w9WgXcQ"
    },
    {
        "id": 46,
        "title": "International Space Agency Announces Mars Mission",
        "slug": "international-post-10",
        "excerpt": "Historic space exploration project receives global support.",
        "content": "<p>Historic space exploration project receives global support.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=500&fit=crop",
        "categoryId": 5,
        "categoryName": "International",
        "language": "en",
        "postType": "article",
        "viewCount": 2202,
        "publishedAt": "2026-02-07T16:00:00Z",
        "createdAt": "2026-02-07T15:00:00Z"
    },
    {
        "id": 47,
        "title": "ජාත්‍යන්තර සංගීත උළෙල සාර්ථකව පවත්වයි",
        "slug": "international-post-11",
        "excerpt": "ලෝක ප්‍රසිද්ධ කලාකරුවන් සහභාගී වූ සංගීත උළෙල.",
        "content": "<p>ලෝක ප්‍රසිද්ධ කලාකරුවන් සහභාගී වූ සංගීත උළෙල.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=500&fit=crop",
        "categoryId": 5,
        "categoryName": "International",
        "language": "si",
        "postType": "audio",
        "viewCount": 2239,
        "publishedAt": "2026-02-07T13:00:00Z",
        "createdAt": "2026-02-07T12:00:00Z",
        "audioId": "60ItHLz5WEA"
    },
    {
        "id": 48,
        "title": "Global Trade Organization Reports Economic Growth",
        "slug": "international-post-12",
        "excerpt": "International trade volumes reach record highs.",
        "content": "<p>International trade volumes reach record highs.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=500&fit=crop",
        "categoryId": 5,
        "categoryName": "International",
        "language": "en",
        "postType": "article",
        "viewCount": 2276,
        "publishedAt": "2026-02-07T10:00:00Z",
        "createdAt": "2026-02-07T09:00:00Z"
    },
    {
        "id": 49,
        "title": "නව තාක්ෂණික නවෝත්පාදන ප්‍රදර්ශනය",
        "slug": "other-post-1",
        "excerpt": "නවීන තාක්ෂණික නවෝත්පාදන ප්‍රදර්ශනය පැවැත්වේ.",
        "content": "<p>නවීන තාක්ෂණික නවෝත්පාදන ප්‍රදර්ශනය පැවැත්වේ.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=500&fit=crop",
        "categoryId": 6,
        "categoryName": "Other",
        "language": "si",
        "postType": "article",
        "viewCount": 2313,
        "publishedAt": "2026-02-07T07:00:00Z",
        "createdAt": "2026-02-07T06:00:00Z"
    },
    {
        "id": 50,
        "title": "Local Food Festival Celebrates Culinary Diversity",
        "slug": "other-post-2",
        "excerpt": "Traditional and modern cuisines showcase cultural heritage.",
        "content": "<p>Traditional and modern cuisines showcase cultural heritage.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=500&fit=crop",
        "categoryId": 6,
        "categoryName": "Other",
        "language": "en",
        "postType": "video",
        "viewCount": 2350,
        "publishedAt": "2026-02-07T04:00:00Z",
        "createdAt": "2026-02-07T03:00:00Z",
        "videoId": "jNQXAC9IVRw"
    },
    {
        "id": 51,
        "title": "ක්‍රීඩා තරඟාවලිය සාර්ථකව අවසන් වේ",
        "slug": "other-post-3",
        "excerpt": "ජාතික ක්‍රීඩා තරඟාවලිය විශිෂ්ට ලෙස සම්පූර්ණ වේ.",
        "content": "<p>ජාතික ක්‍රීඩා තරඟාවලිය විශිෂ්ට ලෙස සම්පූර්ණ වේ.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=500&fit=crop",
        "categoryId": 6,
        "categoryName": "Other",
        "language": "si",
        "postType": "audio",
        "viewCount": 2387,
        "publishedAt": "2026-02-07T01:00:00Z",
        "createdAt": "2026-02-07T00:00:00Z",
        "audioId": "60ItHLz5WEA"
    },
    {
        "id": 52,
        "title": "Art Exhibition Features Contemporary Local Artists",
        "slug": "other-post-4",
        "excerpt": "Emerging artists gain recognition through major showcase.",
        "content": "<p>Emerging artists gain recognition through major showcase.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=500&fit=crop",
        "categoryId": 6,
        "categoryName": "Other",
        "language": "en",
        "postType": "article",
        "viewCount": 2424,
        "publishedAt": "2026-02-06T22:00:00Z",
        "createdAt": "2026-02-06T21:00:00Z"
    },
    {
        "id": 53,
        "title": "සංගීත උළෙල දහස් ගණනක් ආකර්ෂණය කරයි",
        "slug": "other-post-5",
        "excerpt": "ජාතික සංගීත උළෙල විශාල ජනප්‍රියත්වයක් ලබයි.",
        "content": "<p>ජාතික සංගීත උළෙල විශාල ජනප්‍රියත්වයක් ලබයි.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&h=500&fit=crop",
        "categoryId": 6,
        "categoryName": "Other",
        "language": "si",
        "postType": "video",
        "viewCount": 2461,
        "publishedAt": "2026-02-06T19:00:00Z",
        "createdAt": "2026-02-06T18:00:00Z",
        "videoId": "dQw4w9WgXcQ"
    },
    {
        "id": 54,
        "title": "Science Fair Highlights Student Innovation",
        "slug": "other-post-6",
        "excerpt": "Young scientists present groundbreaking research projects.",
        "content": "<p>Young scientists present groundbreaking research projects.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=500&fit=crop",
        "categoryId": 6,
        "categoryName": "Other",
        "language": "en",
        "postType": "article",
        "viewCount": 2498,
        "publishedAt": "2026-02-06T16:00:00Z",
        "createdAt": "2026-02-06T15:00:00Z"
    },
    {
        "id": 55,
        "title": "පොත් ප්‍රදර්ශනය සාහිත්‍ය ප්‍රේමීන් ආකර්ෂණය කරයි",
        "slug": "other-post-7",
        "excerpt": "වාර්ෂික පොත් ප්‍රදර්ශනය විශාල සාර්ථකත්වයක් ලබයි.",
        "content": "<p>වාර්ෂික පොත් ප්‍රදර්ශනය විශාල සාර්ථකත්වයක් ලබයි.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&h=500&fit=crop",
        "categoryId": 6,
        "categoryName": "Other",
        "language": "si",
        "postType": "audio",
        "viewCount": 2535,
        "publishedAt": "2026-02-06T13:00:00Z",
        "createdAt": "2026-02-06T12:00:00Z",
        "audioId": "60ItHLz5WEA"
    },
    {
        "id": 56,
        "title": "Film Festival Showcases Independent Cinema",
        "slug": "other-post-8",
        "excerpt": "Local filmmakers receive international recognition.",
        "content": "<p>Local filmmakers receive international recognition.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800&h=500&fit=crop",
        "categoryId": 6,
        "categoryName": "Other",
        "language": "en",
        "postType": "article",
        "viewCount": 2572,
        "publishedAt": "2026-02-06T10:00:00Z",
        "createdAt": "2026-02-06T09:00:00Z"
    },
    {
        "id": 57,
        "title": "ක්‍රීඩා පුහුණු මධ්‍යස්ථානය විවෘත කෙරේ",
        "slug": "other-post-9",
        "excerpt": "නව ක්‍රීඩා පුහුණු මධ්‍යස්ථානය තරුණයින් සඳහා විවෘත වේ.",
        "content": "<p>නව ක්‍රීඩා පුහුණු මධ්‍යස්ථානය තරුණයින් සඳහා විවෘත වේ.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=500&fit=crop",
        "categoryId": 6,
        "categoryName": "Other",
        "language": "si",
        "postType": "video",
        "viewCount": 2609,
        "publishedAt": "2026-02-06T07:00:00Z",
        "createdAt": "2026-02-06T06:00:00Z",
        "videoId": "dQw4w9WgXcQ"
    },
    {
        "id": 58,
        "title": "Fashion Week Highlights Local Design Talent",
        "slug": "other-post-10",
        "excerpt": "Designers present innovative collections to global audience.",
        "content": "<p>Designers present innovative collections to global audience.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=500&fit=crop",
        "categoryId": 6,
        "categoryName": "Other",
        "language": "en",
        "postType": "article",
        "viewCount": 2646,
        "publishedAt": "2026-02-06T04:00:00Z",
        "createdAt": "2026-02-06T03:00:00Z"
    },
    {
        "id": 59,
        "title": "සෞඛ්‍ය දැනුවත් කිරීමේ වැඩසටහන ආරම්භ වේ",
        "slug": "other-post-11",
        "excerpt": "ජනතාව සෞඛ්‍ය දැනුවත් කිරීම සඳහා නව වැඩසටහනක්.",
        "content": "<p>ජනතාව සෞඛ්‍ය දැනුවත් කිරීම සඳහා නව වැඩසටහනක්.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=500&fit=crop",
        "categoryId": 6,
        "categoryName": "Other",
        "language": "si",
        "postType": "audio",
        "viewCount": 2683,
        "publishedAt": "2026-02-06T01:00:00Z",
        "createdAt": "2026-02-06T00:00:00Z",
        "audioId": "60ItHLz5WEA"
    },
    {
        "id": 60,
        "title": "Technology Expo Attracts Thousands of Visitors",
        "slug": "other-post-12",
        "excerpt": "Latest innovations in tech showcased at annual event.",
        "content": "<p>Latest innovations in tech showcased at annual event.</p><p>Full article content would go here with more details about the story.</p>",
        "featuredImage": "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=500&fit=crop",
        "categoryId": 6,
        "categoryName": "Other",
        "language": "en",
        "postType": "article",
        "viewCount": 2720,
        "publishedAt": "2026-02-05T22:00:00Z",
        "createdAt": "2026-02-05T21:00:00Z"
    }
];

// Mock users with different roles for testing RBAC
export const mockUsers = [
    {
        id: 1,
        email: 'superadmin@darkroom.lk',
        password: 'admin123',
        role: 'super_admin',
        name: 'Super Admin',
    },
    {
        id: 2,
        email: 'admin@darkroom.lk',
        password: 'admin123',
        role: 'admin',
        name: 'Admin User',
    },
    {
        id: 3,
        email: 'editor@darkroom.lk',
        password: 'editor123',
        role: 'editor',
        name: 'Editor User',
    },
    {
        id: 4,
        email: 'user@darkroom.lk',
        password: 'user123',
        role: 'user',
        name: 'Regular User',
    },
];

// Helper function to get user by email
export const getUserByEmail = (email) => {
    return mockUsers.find(user => user.email === email);
};

// Backward compatibility - export first admin user as mockUser
export const mockUser = mockUsers[1];

// Helper function to get posts by category
export const getPostsByCategory = (categorySlug) => {
    if (categorySlug === 'home') {
        return mockPosts;
    }
    return mockPosts.filter(post =>
        post.categoryName.toLowerCase().replace(' ', '-') === categorySlug
    );
};

// Helper function to get posts by type
export const getPostsByType = (postType) => {
    return mockPosts.filter(post => post.postType === postType);
};

// Helper function to get post type statistics
export const getPostTypeStats = () => {
    const stats = {
        article: 0,
        video: 0,
        audio: 0,
        total: mockPosts.length
    };
    
    mockPosts.forEach(post => {
        if (post.postType === 'article') stats.article++;
        else if (post.postType === 'video') stats.video++;
        else if (post.postType === 'audio') stats.audio++;
    });
    
    return stats;
};

// Helper function to get single post
export const getPostBySlug = (slug) => {
    return mockPosts.find(post => post.slug === slug);
};

// Helper function to get featured posts
export const getFeaturedPosts = (limit = 3) => {
    return mockPosts.slice(0, limit);
};

// Helper function to get latest posts
export const getLatestPosts = (limit = 6) => {
    return [...mockPosts]
        .sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt))
        .slice(0, limit);
};

// Helper function to get related posts
export const getRelatedPosts = (postId, categoryId, limit = 3) => {
    return mockPosts
        .filter(post => post.id !== postId && post.categoryId === categoryId)
        .slice(0, limit);
};

// Increment view count (mock implementation)
export const incrementViewCount = (postId) => {
    const post = mockPosts.find(p => p.id === postId);
    if (post) {
        post.viewCount += 1;
    }
    return post;
};
